name: EPyTodo

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
      - 'gai-**'

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Push Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: "1101469524231991429"
          webhook_token: "Xyt9QMpAAhHmLpCv-ePMd43M59TLzQu1Rb45yIBrqSTizhAVYa4eXOvt7qGvZjd5aVy3"
          username: "GitHub"
          avatar_url: "https://cdn.discordapp.com/avatars/1098935462724382750/df91181b3f1cf0ef1592fbe18e0962d7.webp"
          color: 5865F2
          message: "${{ github.event.pusher.name }} pushed to ${{ github.ref_name }}"
