version: "3"

services:

  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - poll-tier

  
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - poll-tier
    
  worker:
    build: ./worker
    restart: always
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-tier
      - result-tier
  
  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
    
networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:

