#COMPILATION:
FROM maven:3.8.4-jdk-11-slim AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:resolve

COPY src/ ./src/

RUN mvn package

#RUN
FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder /app/target/worker-jar-with-dependencies.jar .

EXPOSE 80

CMD ["java", "-jar", "worker-jar-with-dependencies.jar"]

