#!/usr/bin/python3

##
## EPITECH PROJECT, 2023
## 104intersection
## File description:
## MAT Project
##

from sys import *
import math
from os import *
from random import *
import usage

if (len(argv) != 9):
    exit (84)

def     sphere():
    Mx = int(argv[2])
    My = int(argv[3])
    Mz = int(argv[4])
    Vx = int(argv[5])
    Vy = int(argv[6])
    Vz = int(argv[7])
    p = int(argv[8])
    
    print ("Sphere of radius " + "%.0f" % p)
    print ("Line passing through the (" + "%.0f" % Mx + "," + " " + "%.0f" % My
              + "," + " "+ "%.0f" % Mz + ") parallel to the vector ("
              + "%.0f" % Vx + "," + " " + "%.0f" % Vy + "," +  " " + "%.0f" % Vz + ")")

    Vx_a = (Vx) ** 2
    Vx_b = (2 * Vx * Mx)
    Vx_c = (Mx) ** 2
                        
    Vy_a = (Vy) ** 2
    Vy_b = (2 * Vy * My)
    Vy_c = (My) ** 2

    Vz_a = (Vz) ** 2
    Vz_b = (2 * Vz * Mz)
    Vz_c = (Mz) ** 2

    a = Vx_a + Vy_a + Vz_a
    b = Vx_b + Vy_b + Vz_b
    c = Vx_c + Vy_c + Vz_c
    c = c - (p) ** 2
    delta = (b) ** 2 - (4 * a * c)

    if (delta > 0):
        x1 = (float(-b) - float(math.sqrt(delta)))/(2 * float(a))
        x2 = (float(-b) + float(math.sqrt(delta)))/(2 * float(a))
        x = Vx * x1 + Mx
        y = Vy * x1 + My
        z = Vz * x1 + Mz
        u = Vx * x2 + Mx
        v = Vy * x2 + My
        w = Vz * x2 + Mz

        print ("2 intersection points :")
        print ("(" + "%.3f" % u + ", " + "%.3f" % v + ", " + "%.3f" % w + ")")
        print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")

    elif (delta == 0):
        t = (-float(b))/(2 * float(a))
        x = Vx * t + Mx
        y = Vy * t + My
        z = Vz * t + Mz

        print ("1 intersection point :")
        print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")
    else:
        print ("No intersection point.")

###################################################################################

def     cylindre():
    Mx = int(argv[2])
    My = int(argv[3])
    Mz = int(argv[4])
    Vx = int(argv[5])
    Vy = int(argv[6])
    Vz = int(argv[7])
    p = int(argv[8])
    
    print ("Cylinder of radius " + "%.0f" % p)
    print ("Line passing through the (" + "%.0f" % Mx + "," + "%.0f" % My
              + "," + "%.0f" % Mz + ") parallel to the vector ("
              + "%.0f" % Vx + "," + "%.0f" % Vy + "," + "%.0f" % Vz + ")")

    Vx_a = (Vx) ** 2
    Vx_b = (2 * Vx * Mx)
    Vx_c = (Mx) ** 2

    Vy_a = (Vy) ** 2
    Vy_b = (2 * Vy * My)
    Vy_c = (My) ** 2

    a = Vx_a + Vy_a
    b = Vx_b + Vy_b
    c = Vx_c + Vy_c
    c = c - (p) ** 2
    delta = (b) ** 2 - (4 * a * c)

    if (delta > 0):
        x1 = float(-b - math.sqrt(delta))/(2 * a)
        x2 = float(-b + math.sqrt(delta))/(2 * a)
        x = Vx * x1 + Mx
        y = Vy * x1 + My
        z = Vz * x1 + Mz
        u = Vx * x2 + Mx
        v = Vy * x2 + My
        w = Vz * x2 + Mz
        
        print ("2 intersection points :")
        print ("(" + "%.3f" % u + ", " + "%.3f" % v + ", " + "%.3f" % w + ")")
        print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")

    elif (delta == 0):
        if ((2 * float(a)) != 0):
            t = (-float(b))/(2 * float(a))
            x = Vx * t + Mx
            y = Vy * t + My
            z = Vz * t + Mz
            
            print ("1 intersection point :")
            print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")
        else:
            print ("There is an infinite number of intersection points.")
    else:
        print ("No intersection point.")
        
def     cone():
    Mx = int(argv[2])
    My = int(argv[3])
    Mz = int(argv[4])
    Vx = int(argv[5])
    Vy = int(argv[6])
    Vz = int(argv[7])
    angle = int(argv[8])

    print ("cone of " + "%.0f" % angle + " degree angle")
    print ("Line passing through the (" + "%.0f" % Mx + "," + "%.0f" % My
              + "," + "%.0f" % Mz + ") parallel to the vector ("
              + "%.0f" % Vx + "," + "%.0f" % Vy + "," + "%.0f" % Vz + ")")

    Vx_a = (Vx) ** 2
    Vx_b = (2 * Vx * Mx)
    Vx_c = (Mx) ** 2

    Vy_a = (Vy) ** 2
    Vy_b = (2 * Vy * My)
    Vy_c = (My) ** 2

    Vz_a = (Vz) ** 2
    Vz_b = (2 * Vz * Mz)
    Vz_c = (Mz) ** 2

    a = Vx_a + Vy_a - (Vz_a * math.tan(math.radians(angle)) ** 2)
    b = Vx_b + Vy_b - (Vz_b * math.tan(math.radians(angle)) ** 2)
    c = Vx_c + Vy_c - (Vz_c * math.tan(math.radians(angle)) ** 2)
    delta = (b) ** 2 - (4 * a * c)
    
    if (delta > 0):
        x1 = (-b - math.sqrt(delta))/(2 * a)
        x2 = (-b + math.sqrt(delta))/(2 * a)
        x = Vx * x1 + Mx
        y = Vy * x1 + My
        z = Vz * x1 + Mz
        u = Vx * x2 + Mx
        v = Vy * x2 + My
        w = Vz * x2 + Mz
        
        print ("2 intersection points :")
        print ("(" + "%.3f" % u + ", " + "%.3f" % v + ", " + "%.3f" % w + ")")
        print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")
        
    elif (delta == 0):
        if (2 * float(a) != 0):
            t = (-float(b))/(2 * float(a))
            x = Vx * t + Mx
            y = Vy * t + My
            z = Vz * t + Mz
        
            print ("1 intersection point :")
            print ("(" + "%.3f" % x + ", " + "%.3f" % y + ", " + "%.3f" % z + ")")
        else:
            print ("There is an infinite number of intersection points.")
    else:
        print ("No intersection point.")

def     true_int(str_av):
    if (str_av[0] == '-'):
        i = 1
    else:
        i = 0
    while (i < len(str_av)):
        if (str_av[i] < '0' or str_av[i] > '9'):
            exit(84)
        i = i + 1;

i = 1
while (i < 9):
    true_int(argv[i])
    i = i + 1

if (int(argv[8]) <= 0):
    exit(84)
if (argv[1] == '1'):
    sphere()
elif (argv[1] == '2'):
    cylindre()
elif (argv[1] == '3'):
    cone()
else:
    exit(84)
