gcc -c my_compute_power_rec.c
gcc -c my_compute_square_root.c
gcc -c my_find_prime_sup.c
gcc -c my_getnbr.c
gcc -c my_is_prime.c
gcc -c my_isneg.c
gcc -c my_put_nbr.c
gcc -c my_putchar.c
gcc -c my_putstr.c
gcc -c my_revstr.c
gcc -c my_showmem.c
gcc -c my_showstr.c
gcc -c my_sort_int_array.c
gcc -c my_str_isalpha.c
gcc -c my_str_islower.c
gcc -c my_str_isnum.c
gcc -c my_str_isprintable.c
gcc -c my_str_isupper.c
gcc -c my_strcapitalize.c
gcc -c my_strcat.c
gcc -c my_strcmp.c
gcc -c my_strcpy.c
gcc -c my_strlen.c
gcc -c my_strlowcase.c
gcc -c my_strncat.c
gcc -c my_strncmp.c
gcc -c my_strcpy.c
gcc -c my_strupcase.c
gcc -c my_swap.c
ar rc libmy.a my_compute_power_rec.o my_compute_square_root.o my_find_prime_sup.o my_getnbr.o my_is_prime.o my_isneg.o my_put_nbr.o my_putchar.o my_putstr.o my_revstr.o my_showmem.o my_showstr.o my_sort_int_array.o my_str_isalpha.o my_str_islower.o my_str_isnum.o my_str_isprintable.o my_str_isupper.o my_strcapitalize.o my_strcat.o my_strcmp.o my_strcpy.o my_strlen.o my_strlowcase.o my_strncat.o my_strncmp.o my_strcpy.o my_strupcase.o my_swap.o
