##
## EPITECH PROJECT, 2022
## antman
## File description:
## Makefile of antman
##

all:
	cd antman && make all
	cd giantman && make all

clean:
	cd antman && make clean
	cd giantman && make clean

fclean:	clean
	cd antman && make fclean
	cd giantman && make fclean

re:	fclean all
